services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: talkative-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        networks:
            - talkative-network

    # Nginx Service
    nginx:
        build:
            context: ./docker/nginx/
            dockerfile: Dockerfile
        container_name: talkative-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/html/
        ports:
            - 80:80
            - 443:443
        networks:
            - talkative-network

    # MySQL Service
    database:
        image: mysql:8.2.0
        container_name: talkative-mysql
        restart: unless-stopped
        tty: true
        ports:
            - ${DB_PORT}:3306
        volumes:
            - talkative-mysql-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        networks:
            - talkative-network

    # Redis Service
    redis:
        image: redis:7.2.3
        container_name: talkative-redis
        restart: unless-stopped
        tty: true
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - talkative-network

    # Soketi Service
    soketi:
        image: quay.io/soketi/soketi:1.0-16-alpine
        container_name: talkative-soketi
        restart: unless-stopped
        tty: true
        ports:
            - ${SOKETI_PORT:-6001}:6001
            - ${SOKETI_METRICS_SERVER_PORT:-9601}:9601
        environment:
            - SOKETI_DEBUG=${SOKETI_DEBUG:-1}
            - SOKETI_METRICS_SERVER_PORT=${SOKETI_METRICS_SERVER_PORT:-9601}
        networks:
            - talkative-network


# Docker volumes
volumes:
    talkative-mysql-data:

# Docker newtorks
networks:
    talkative-network:
        driver: bridge
